# Generated by Django 5.0.6 on 2025-01-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_hr_side', '0004_customuser_alter_professional_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='resume_content',
            field=models.CharField(default=None, max_length=1000000),
        ),
    ]
