# Generated by Django 5.0.6 on 2025-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_hr_side', '0008_alter_professional_resume_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='resume_content',
        ),
        migrations.AddField(
            model_name='student',
            name='resume_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
