# Generated by Django 5.0.6 on 2025-01-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_hr_side', '0009_remove_professional_resume_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='resume_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
